---
output: github_document
bibliography: russia-elections.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# russia-elections

This repo uses the Significance article "Putin's peaks" (@doi:10.1111/j.1740-9713.2018.01141.x) as a motivating example in ST541 Probability, Simulation and Computing in Statistics.

The original article code can be found at: https://github.com/dkobak/elections/

# Outline

1. Get into groups of 3-4, each group will need a laptop.

2. **Group Discussion** Discuss the answers to pre-lecture activity.

3. **Class Discussion** Review answers and narrow focus to voter turnout in 2018.

4. **Group Activity** 
    
    * Access the class workspace on RStudio cloud.  Open `russia-elections` project and save a copy.
    * Knit `01_data-import.Rmd`.  What is reported by the polling stations? How is the turnout calculated from the available data? Compare the figures, does this data seem to match the paper?

5. **Class Discssion** Clarify objective and relevant data.

6. **Group Activity** `02_explore-analysis.Rmd` Find the number of *integer turnouts* in 2018.

7. **Class Discssion** Why is this hard? 

8. **Class Discussion** Review Monte Carlo approach.  

9. **Group Activity** How would you simulate turnout at a polling station?  

10. **Group Activity** Simulate a set of turnouts and find number of integer turnouts.

11. **Class Discussion** Collect integer turnouts, compare to observed integer turnout.  Show a larger simulation.

12. **Class Discussion** What would be an alternative approach to the simulation?

13. Review main themes of course:
    
    * **Computational alternatives to analytical techniques**: specific algorithms commonly encountered in statistics.
    * **Programming for statistical computation**: code that is correct, clear, and if neccessary, fast.
    * **Best practices for computational projects**: organization and workflows for projects that are easy to reproduce, share and collaborate on.
    

## References